### ISSUE TITLE
Easier way to add and manipulate new nodes

### ISSUE THREAD

**Issue by matthijskooijman** [scotteh/php-dom-wrapper#16]
Every now and then, I find myself writing code that creates a new element, sets some data on it, and adds it to the document. E.g. something like this:

                $div = $doc->createElement('div');
                $div->setAttr('id', 'foo');
                $doc->findXPath('/body')->append($div);

I wonder if this could be more compact with php-dom-wrapper? Jquery seems to [have appendTo() for this](https://stackoverflow.com/a/2159376/740048). Similar to that, I would like to write:

    DOMWrap\create('div')->setAttr('id', 'foo')->appendTo($doc->findXPath('/body');

Note that this contains two new parts: `DOMWrap\create` to create a new element and `appendTo` to append an element to an existing element.

`appendTo` is probably easy, the `create` might need some more thought:
 - Its name might need improvement, something short like jquery's `$()` is nice, but probably not essential.
 - Maybe it should (also) accept a html string or have a second variant that does so (so you can do things like `DOMWrap\create('<div>foo</foo>')` as well.
 - Since there is no reference to the existing document, this will need to create a new document, and appendTo will have to move over the elements to the existing documents (which I think already happens with the current append and similar methods).
 - Maybe the existing code could already do this using `new DomWrap\Document()->html('<div>')`, but that is a bit verbose perhaps?

Love to hear your thoughts on this :-)

**Comment by matthijskooijman** [comment]
I just realized that for the example I gave, you could perhaps also write something like:

    $doc->findXPath('/body')->append((new DOMWrap\Document())->createElement('div')->setAttr('id', 'foo'));

And not need `appendTo()` at all. However, one other usecase is where you want to do a bit more processing on the added element, e.g.:

    $meta = DOMWrap\create('meta')->appendTo($doc->findXPath('/head'));
    $meta->setAttr('http-equiv', "Content-Type");
    $meta->setAttr('content', "text/html; charset=utf-8");

In this example, I could create the element and append it in one line, and then store a reference to fill the element next. For me, this is a good balance between conciseness and clarity of code, but it needs an `appendTo()`.

Note that the first example in this comment won't even work right now. It seems that `(new DOMWrap\Document())->createElement('div')` messes something up in garbage collection, so that gives you an element that has no `ownerDocument` and if you call `document()` on it, you get a `DOMDocument` rather than a `DOMWrap\Document`...

**Comment by scotteh** [comment]
Implemented a rather simple ::create() function.

This should fix the issue you were seeing with `(new DOMWrap\Document())->createElement('div')` vs `$doc = new DOMWrap\Document(); $newEl = ->createElement('div');` and `...->document()` returning a DOMDocument object rather than a DOMWrap\Document one. As you alluded to this issue appears to be somewhat PHP related. Most likely to do with the DOM module combined with `DOMDocument::registerNodeClass()` which this library relies on.

You should be able to backport this change quite easily given that it is effectively a wrapper around an internal function that exists in almost all versions.

There is one caveat: While testing this I uncovered an issue with attaching a created \DOMNode like object more than once.

eg:
``` php
$contents = '
<html>
<ul>
<li></li>
<li></li>
</ul>
</html>
';
$doc = new Document();
$doc->html($contents);
$newNode = $doc->create('<span />');
$nodes = $doc->find('li');
$nodes->append($newNode);
```

Would only append the new element to the last 'li' element matched, rather than both.

The following would work OK:
``` php
$contents = '
<html>
<ul>
<li></li>
<li></li>
</ul>
</html>
';
$doc = new Document();
$doc->html($contents);
$nodes = $doc->find('li');
$nodes->append('<span />);
```

Will review your `appendTo()` (and by extension `prependTo()`) suggestion.

**Comment by christianmagill** [comment]
@scotteh, How would you go about creating the text contents of a new node? For instance, the text of a label.

**Comment by scotteh** [comment]
Pushed a fix for the `(new Document)->createElement()` issue you picked up. See commit e56646c9bdda2baed3547174c30b4f41394c78e0.
