### ISSUE TITLE
Wrong encoding when add elements with text

### ISSUE THREAD

**Issue by LoranRendel** [scotteh/php-dom-wrapper#22]
```php
$doc = new \DOMWrap\Document();
$doc->append("<div>Tést</div>");
$doc->append($doc->create("<div></div>")->text("Tést"));
echo $doc->html();
```

Result:
```
TÃ©st
Tést
```

**Comment by kaeverens** [comment]
I just encountered and fixed this in my own project as well.

the problem is in file `src/Traits/ManipulationTrait.php`. the function `nodesFromHtml()` creates a psuedo Document object to embed the HTML in and then returns the created nodes. but the Document object is not passed the charset of the parent document `$doc`.

workaround: change your second line to this:

```
$doc->append("<?xml encoding='UTF-8'><div>Tést</div>");
```

solution: the author of the library will need to change the `nodesFromHtml` function to properly set the charset before the HTML is set.
